# Generated by Django 4.1 on 2022-09-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_about_description_alter_about_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
