# Generated by Django 4.1 on 2022-09-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_about_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile',
            field=models.CharField(max_length=50),
        ),
    ]
