# Generated by Django 4.1 on 2022-09-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_portfolio_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='created',
            field=models.DateTimeField(default=0),
        ),
    ]
