# Generated by Django 4.1 on 2022-09-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_portfolio_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='exit', upload_to='portfolio'),
            preserve_default=False,
        ),
    ]
