# Generated by Django 4.1 on 2022-09-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_contact_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='linkin',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='contact_us',
            old_name='twiter',
            new_name='twitter',
        ),
    ]
