# Generated by Django 4.1 on 2022-09-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_linkin_contact_us_linkedin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='linkedin',
            new_name='linedin',
        ),
        migrations.RenameField(
            model_name='contact_us',
            old_name='twitter',
            new_name='twiter',
        ),
    ]
