# Generated by Django 4.1 on 2022-09-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_linkedin_contact_us_linedin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='linedin',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='contact_us',
            old_name='twiter',
            new_name='twitter',
        ),
    ]
