# Generated by Django 4.1 on 2022-09-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='message',
        ),
    ]
