# Generated by Django 4.1 on 2022-09-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_body_message_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('sub_title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='blog_picturr')),
                ('sub_image', models.ImageField(upload_to='blog_picture')),
                ('author', models.CharField(max_length=38)),
                ('create_date', models.DateTimeField(default=0)),
            ],
        ),
    ]
