# Generated by Django 4.1 on 2022-09-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
