# Generated by Django 4.1 on 2022-09-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_counters_years_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counters',
            name='years_experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='counters',
            name='total_clients',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='counters',
            name='works_completed',
            field=models.IntegerField(null=True),
        ),
    ]
