# Generated by Django 4.1 on 2022-09-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_counters_years_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counters',
            name='award_won',
            field=models.IntegerField(null=True),
        ),
    ]
