# Generated by Django 4.1 on 2022-09-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_counters_award_won'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author1', models.CharField(max_length=42)),
                ('description1', models.TextField()),
                ('author2', models.CharField(max_length=20)),
                ('description2', models.TextField()),
            ],
        ),
    ]
