# Generated by Django 4.1 on 2022-09-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='sub_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
