# Generated by Django 4.1 on 2022-09-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_services_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='sub_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
