# Generated by Django 4.1 on 2022-09-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_services_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
