# Generated by Django 4.1 on 2022-09-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_services_sub_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='sub_title',
        ),
    ]
