# Generated by Django 4.1 on 2022-09-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_services_sub_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=100)),
            ],
        ),
    ]
