# Generated by Django 4.1.1 on 2022-09-24 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_sub_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'در مورد من', 'verbose_name_plural': 'در موارد من'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'وبلاگ', 'verbose_name_plural': 'وبلاگ'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': 'تماس', 'verbose_name_plural': 'تماس ها'},
        ),
        migrations.AlterModelOptions(
            name='counters',
            options={'verbose_name': 'شمارنده', 'verbose_name_plural': 'شمارنده'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'پاورقی', 'verbose_name_plural': 'پاورقیها'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام ها'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'نمونه فعالیت', 'verbose_name_plural': 'نمونه فعالیت ها'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'فعالیت', 'verbose_name_plural': 'فعالیت ها'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت ها'},
        ),
        migrations.AlterModelOptions(
            name='sub_title',
            options={'verbose_name': 'عنوان فرعی', 'verbose_name_plural': 'عناوین فرعی'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'جایزه', 'verbose_name_plural': 'جوایز'},
        ),
    ]
