# Generated by Django 4.1 on 2022-09-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0034_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('project_date', models.DateTimeField(auto_now_add=True)),
                ('web_address', models.URLField()),
                ('title', models.CharField(max_length=42)),
                ('description', models.TextField()),
                ('category', models.ManyToManyField(to='home.category')),
            ],
        ),
    ]
