# Generated by Django 4.1.1 on 2022-09-24 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='portfolio_info',
            options={'verbose_name': 'نمونه فعالیت', 'verbose_name_plural': 'نمونه فعالیت ها'},
        ),
    ]
